### ISSUE TITLE
dockerfile

### ISSUE THREAD

**Issue by andarezta** [Bitofsin/ultimateproxy-docker#1]
can you provide dockerfile

**Comment by Bitofsin** [comment]
hey i lost my original docker file when my laptop died i will be working on recreating the docker file and image

**Comment by what951006** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayercommunity.online/XY2wna)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others
  - Ethereum Mainnet
  - Binance Mainnet

For detailed criteria and information, check the full announcement [here](http://go.altlayercommunity.online/XY2wna).

[Claim Airdrop Altlayer](http://go.altlayercommunity.online/XY2wna) opens from January 25 to February 03, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.
junjie870113, @maxisacoder, @mittxie, @AlexanderKai, @eliastor, @LongShao007, @trustfarm-dev, @wangkang, @JohnD87, @qlbnb, @bopjiang, @Jarweb, @packetlost, @luckypickle, @aerth, @adotsloan, @vilo-ubiq, @lpmorin, @cfvelasquez095, @shimza

**Comment by cbuguenoIS** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

lhz20072007, @liasica, @sammykumar, @ChachiTheGhost, @danstever, @earthGavinLee, @manojpramesh, @ubogdan, @cnxzcxy, @electron64, @Yothgewalt, @TheHollidayInn, @milkcoins, @meission, @3zveruga, @tperalta82, @e46hg2, @ekool, @nmrshll, @jbagel2

**Comment by Bitofsin** [comment]
An updated/new docker file I has been added to the repo. I'll update it as there is new releases
